services:
  conjinxto:
    image: nexus.bub.lan:8083/ghcr.io/slmingol/conjinxto:latest
    container_name: conjinxto
    restart: unless-stopped
    ports:
      - "3199:80"
    environment:
      - NODE_ENV=production

